services:
  
  db:
    image: mongo:5.0.2
    restart: always
    environment:
      MONGO_INITDB_DATABASE  : ECommerceDb 
    ports:
      - 27017:27017
    volumes:
      - ~/mongo:/data/db
 
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
 
volumes:
  redis-data:
